import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { api, type RouterOutputs} from "~/utils/api";
import WorksList from "~/components/worksList";
import NavBar from "~/components/NavBar";
import Daily from "~/components/daily";
import UploadComponent from "~/components/uploadComponent";
const Home: NextPage = (props) => {
  

  return (
    <>
      <Head>
        <title>KeepKing Kasa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="flex min-w-full h-max flex-col items-center justify-start ">
      
      
      <UploadComponent></UploadComponent>
      </main>
    </>
  );
};

export default Home;



